/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_laser_dot_brightness: 750
      i_enable_diagnostics: true
      i_enable_imu: false
    rgb:
      # i_width: 1920
      # i_height: 1080
      i_enable_nn: false
      i_resolution: 1080P
      i_fps: 30.0
      i_output_isp: true
      r_set_man_focus: true
      r_focus: 121
    right:
      i_fps: 30.0
    left:
      i_fps: 30.0
    stereo:
      i_align_depth: true
      i_subpixel: false
      i_depth_preset: HIGH_DENSITY
      i_lr_check: true
      i_enable_spatial_nn: false
      # i_width: 1920
      # i_height: 1080
      i_fps: 30.0
      i_publish_synced_rect_pair: false